using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// Runtime presenter for the survival-game HUD. The scene layout is generated by
/// SurvivalHUDBuilder and all references remain editable in the Inspector.
/// </summary>
public class SurvivalHUD : MonoBehaviour
{
    [Header("Gameplay References")]
    [SerializeField] private PlayerHealth playerHealth;
    [SerializeField] private XPSystem xpSystem;
    [SerializeField] private WeaponInventory weaponInventory;
    [SerializeField] private PlayerTomeInventory tomeInventory;
    [SerializeField] private PlayerItemInventory itemInventory;
    [SerializeField] private PlayerCurrency playerCurrency;

    [Header("HUD References")]
    [SerializeField] private Image healthFill;
    [SerializeField] private TMP_Text healthText;
    [SerializeField] private Image experienceFill;
    [SerializeField] private Color experienceFillColor = new Color32(34, 217, 111, 255);
    [SerializeField, Min(1f)] private float experienceFillAnimationSpeed = 10f;
    [SerializeField] private TMP_Text experienceText;
    [SerializeField] private TMP_Text levelText;
    [SerializeField] private TMP_Text timerText;
    [SerializeField] private TMP_Text goldText;

    [SerializeField] private TMP_Text coinsText;
    [SerializeField] private TMP_Text enemiesDefeatedText;

    [Header("Health Bar Animation")]
    [SerializeField, Min(1f)] private float healthFillAnimationSpeed = 10f;
    private float targetHealthFill = 1f;
    private float currentHealthFill = 1f;
    [SerializeField] private HUDItemSlot[] weaponSlots = new HUDItemSlot[4];
    [SerializeField] private HUDItemSlot[] tomeSlots = new HUDItemSlot[4];
    [SerializeField] private RectTransform itemSlotsPanel;
    private RectTransform itemSlotsContent;
    private ScrollRect itemSlotsScrollRect;


    private const int StartingVisibleInventorySlots = 2;
    private const int MaximumInventorySlots = 4;
    private readonly List<HUDItemSlot> itemSlots = new List<HUDItemSlot>();

    private float elapsedTime;
    private float targetExperienceFill;
    private float postLevelExperienceFill;
    private bool isAnimatingLevelFill;
    [SerializeField] private TMP_FontAsset displayFont;

    private void Awake()
    {
        ApplyDisplayFont();
        ConfigureExperienceBar();
        ConfigureHealthBar();

        if (playerHealth == null)
            playerHealth = FindFirstObjectByType<PlayerHealth>();

        if (xpSystem == null)
            xpSystem = FindFirstObjectByType<XPSystem>();

        if (weaponInventory == null)
            weaponInventory = FindFirstObjectByType<WeaponInventory>();

        if (tomeInventory == null)
            tomeInventory = FindFirstObjectByType<PlayerTomeInventory>();

        if (itemInventory == null)
            itemInventory = FindFirstObjectByType<PlayerItemInventory>();

        if (playerCurrency == null)
            playerCurrency = FindFirstObjectByType<PlayerCurrency>();

        FindWeaponSlots();
        FindTomeSlots();
        FindOrCreateItemSlotsPanel();
    }

    private void ConfigureHealthBar()
    {
        if (healthFill == null) return;

        healthFill.type = Image.Type.Simple;
        
        RectTransform fillRect = healthFill.rectTransform;
        fillRect.anchorMin = Vector2.zero;
        fillRect.pivot = new Vector2(0f, 0.5f);
        fillRect.offsetMin = Vector2.zero;
        fillRect.offsetMax = Vector2.zero;
        SetHealthBarVisual(1f);
    }

    private void SetHealthBarVisual(float progress)
    {
        if (healthFill == null) return;

        progress = Mathf.Clamp01(progress);
        healthFill.fillAmount = progress;

        RectTransform fillRect = healthFill.rectTransform;
        fillRect.anchorMax = new Vector2(progress, 1f);
        fillRect.offsetMin = Vector2.zero;
        fillRect.offsetMax = Vector2.zero;
    }

    private void ConfigureExperienceBar()
    {
        if (experienceFill == null) return;

        // Resize the actual green rectangle instead of relying only on Image.fillAmount.
        // This also works reliably when the Image has no source sprite assigned.
        experienceFill.type = Image.Type.Simple;
        experienceFill.color = experienceFillColor;

        RectTransform fillRect = experienceFill.rectTransform;
        fillRect.anchorMin = Vector2.zero;
        fillRect.pivot = new Vector2(0f, 0.5f);
        fillRect.offsetMin = Vector2.zero;
        fillRect.offsetMax = Vector2.zero;
        SetExperienceBarVisual(0f);
    }

    private void SetExperienceBarVisual(float progress)
    {
        if (experienceFill == null) return;

        progress = Mathf.Clamp01(progress);
        experienceFill.fillAmount = progress;

        RectTransform fillRect = experienceFill.rectTransform;
        fillRect.anchorMax = new Vector2(progress, 1f);
        fillRect.offsetMin = Vector2.zero;
        fillRect.offsetMax = Vector2.zero;
    }

    private void ApplyDisplayFont()
    {
        if (displayFont == null) return;

        TMP_Text[] labels = GetComponentsInChildren<TMP_Text>(true);
        foreach (TMP_Text label in labels)
        {
            label.font = displayFont;
            label.fontStyle = FontStyles.Normal;
        }
    }

    private void OnEnable()
    {
        FindCoinText();

        if (xpSystem != null)
        {
            xpSystem.OnXPChanged += HandleXPChanged;
            xpSystem.OnLevelUp += HandleLevelUp;
        }

        if (weaponInventory != null)
            weaponInventory.WeaponsChanged += RefreshWeaponSlots;

        if (tomeInventory != null)
            tomeInventory.TomesChanged += RefreshTomeSlots;

        if (itemInventory != null)
            itemInventory.ItemsChanged += RefreshItemSlots;

        if (playerCurrency != null)
        {
            playerCurrency.GoldChanged += RefreshGold;
            playerCurrency.EnemiesDefeatedChanged += RefreshEnemiesDefeated;
            playerCurrency.CoinsChanged += RefreshCoins;
        }

        RefreshExperience(true);
        RefreshWeaponSlots();
        RefreshTomeSlots();
        RefreshItemSlots();
        RefreshProgressCounters();
    }

    private void OnDisable()
    {
        if (xpSystem != null)
        {
            xpSystem.OnXPChanged -= HandleXPChanged;
            xpSystem.OnLevelUp -= HandleLevelUp;
        }

        if (weaponInventory != null)
            weaponInventory.WeaponsChanged -= RefreshWeaponSlots;

        if (tomeInventory != null)
            tomeInventory.TomesChanged -= RefreshTomeSlots;

        if (itemInventory != null)
            itemInventory.ItemsChanged -= RefreshItemSlots;

        if (playerCurrency != null)
        {
            playerCurrency.GoldChanged -= RefreshGold;
            playerCurrency.EnemiesDefeatedChanged -= RefreshEnemiesDefeated;
            playerCurrency.CoinsChanged -= RefreshCoins;
        }
    }

    private void Update()
    {
        elapsedTime += Time.deltaTime;
        RefreshTimer();
        RefreshHealth();
        AnimateExperienceBar();
        AnimateHealthBar();
    }

    private void AnimateHealthBar()
    {
        if (healthFill == null) return;
        
        float blend = 1f - Mathf.Exp(-healthFillAnimationSpeed * Time.unscaledDeltaTime);
        currentHealthFill = Mathf.Lerp(currentHealthFill, targetHealthFill, blend);
        SetHealthBarVisual(currentHealthFill);
    }

    private void AnimateExperienceBar()
    {
        if (experienceFill == null) return;

        float blend = 1f - Mathf.Exp(-experienceFillAnimationSpeed * Time.unscaledDeltaTime);
        float displayedProgress = Mathf.Lerp(experienceFill.fillAmount, targetExperienceFill, blend);
        SetExperienceBarVisual(displayedProgress);

        if (Mathf.Abs(experienceFill.fillAmount - targetExperienceFill) > 0.001f) return;

        SetExperienceBarVisual(targetExperienceFill);

        if (!isAnimatingLevelFill || targetExperienceFill < 1f) return;

        // Show the full bar first, then restart from the left for the new level.
        SetExperienceBarVisual(0f);
        targetExperienceFill = postLevelExperienceFill;
        isAnimatingLevelFill = false;
    }

    private void RefreshTimer()
    {
        if (timerText == null) return;

        int totalSeconds = Mathf.FloorToInt(elapsedTime);
        int minutes = totalSeconds / 60;
        int seconds = totalSeconds % 60;
        timerText.text = $"{minutes:00}:{seconds:00}";
    }

    private void RefreshHealth()
    {
        if (playerHealth == null || playerHealth.stats == null) return;

        float maxHealth = Mathf.Max(1f, playerHealth.stats.FinalHp);
        float currentHealth = Mathf.Clamp(playerHealth.currentHp, 0f, maxHealth);

        targetHealthFill = currentHealth / maxHealth;

        if (healthText != null)
        {
            healthText.text = $"{Mathf.CeilToInt(currentHealth)} / {Mathf.CeilToInt(maxHealth)}";
        }
    }

    private void RefreshExperience(bool immediate = false)
    {
        if (xpSystem == null) return;

        float progress = Mathf.Clamp01(xpSystem.XPProgress);
        targetExperienceFill = progress;

        if (immediate)
            SetExperienceBarVisual(progress);

        if (experienceText != null)
            experienceText.text = $"XP  {xpSystem.CurrentXP} / {xpSystem.XPToNextLevel}";

        if (levelText != null)
            levelText.text = $"LEVEL {xpSystem.CurrentLevel:00}";
    }

    private void HandleXPChanged(int currentXP, int requiredXP)
    {
        float progress = requiredXP > 0
            ? Mathf.Clamp01((float)currentXP / requiredXP)
            : 0f;

        if (currentXP >= requiredXP)
        {
            targetExperienceFill = 1f;
            postLevelExperienceFill = 0f;
            isAnimatingLevelFill = true;
        }
        else if (isAnimatingLevelFill)
        {
            postLevelExperienceFill = progress;
        }
        else
        {
            targetExperienceFill = progress;
        }

        RefreshExperienceText();
    }

    private void HandleLevelUp(int newLevel)
    {
        if (levelText != null)
            levelText.text = $"LEVEL {newLevel:00}";
    }

    private void RefreshExperienceText()
    {
        if (xpSystem == null) return;

        if (experienceText != null)
            experienceText.text = $"XP  {xpSystem.CurrentXP} / {xpSystem.XPToNextLevel}";

        if (levelText != null)
            levelText.text = $"LEVEL {xpSystem.CurrentLevel:00}";
    }

    private void RefreshProgressCounters()
    {
        if (playerCurrency == null)
            return;

        RefreshGold(playerCurrency.Gold);
        RefreshEnemiesDefeated(playerCurrency.EnemiesDefeated);
        RefreshCoins(playerCurrency.Coins);
    }

    private void RefreshGold(int gold)
    {
        if (goldText != null)
            goldText.text = Mathf.Max(0, gold).ToString();
    }

    private void RefreshEnemiesDefeated(int defeated)
    {
        if (enemiesDefeatedText != null)
            enemiesDefeatedText.text = Mathf.Max(0, defeated).ToString();
    }

    private void RefreshCoins(int coins)
    {
        if (coinsText != null)
            coinsText.text = Mathf.Max(0, coins).ToString();
    }

    private void FindCoinText()
    {
        if (coinsText != null)
            return;

        Transform coinAmount = transform.Find("ProgressCounters/CoinCounter/CoinAmount");
        if (coinAmount != null)
            coinsText = coinAmount.GetComponent<TMP_Text>();
    }



    private void FindOrCreateItemSlotsPanel()
    {
        if (itemSlotsPanel == null)
        {
            Transform inventoryPanel = transform.Find("PlayerStatusPanel/InventoryPanel");
            if (inventoryPanel == null)
                return;

            Transform existingPanel = inventoryPanel.Find("ItemSlotsPanel");
            if (existingPanel != null)
            {
                itemSlotsPanel = existingPanel.GetComponent<RectTransform>();
            }
            else
            {
                GameObject panelObject = new GameObject(
                    "ItemSlotsPanel",
                    typeof(RectTransform),
                    typeof(Image),
                    typeof(Mask),
                    typeof(ScrollRect));
                panelObject.transform.SetParent(inventoryPanel, false);
                itemSlotsPanel = panelObject.GetComponent<RectTransform>();

                Image panelImage = panelObject.GetComponent<Image>();
                panelImage.color = new Color(0f, 0f, 0f, 0.28f);
                panelImage.raycastTarget = false;

                Mask mask = panelObject.GetComponent<Mask>();
                mask.showMaskGraphic = false;
            }
        }

        itemSlotsPanel.anchorMin = new Vector2(0f, 1f);
        itemSlotsPanel.anchorMax = new Vector2(1f, 1f);
        itemSlotsPanel.pivot = new Vector2(0.5f, 1f);
        itemSlotsPanel.anchoredPosition = new Vector2(0f, -211f);
        itemSlotsPanel.sizeDelta = new Vector2(0f, 80f);

        if (itemSlotsContent == null)
        {
            Transform existingContent = itemSlotsPanel.Find("Content");
            if (existingContent != null)
                itemSlotsContent = existingContent.GetComponent<RectTransform>();
            else
            {
                GameObject contentObject = new GameObject(
                    "Content",
                    typeof(RectTransform),
                    typeof(HorizontalLayoutGroup));
                contentObject.transform.SetParent(itemSlotsPanel, false);
                itemSlotsContent = contentObject.GetComponent<RectTransform>();
            }
        }

        itemSlotsContent.anchorMin = new Vector2(0f, 0f);
        itemSlotsContent.anchorMax = new Vector2(0f, 1f);
        itemSlotsContent.pivot = new Vector2(0f, 0.5f);
        itemSlotsContent.anchoredPosition = Vector2.zero;
        itemSlotsContent.sizeDelta = new Vector2(344f, 0f);

        HorizontalLayoutGroup layout = itemSlotsContent.GetComponent<HorizontalLayoutGroup>();
        layout.spacing = 8f;
        layout.padding = new RectOffset(4, 4, 0, 0);
        layout.childAlignment = TextAnchor.MiddleLeft;
        layout.childControlWidth = false;
        layout.childControlHeight = false;
        layout.childForceExpandWidth = false;
        layout.childForceExpandHeight = false;

        if (itemSlotsScrollRect == null)
            itemSlotsScrollRect = itemSlotsPanel.GetComponent<ScrollRect>();
        if (itemSlotsScrollRect != null)
        {
            itemSlotsScrollRect.viewport = itemSlotsPanel;
            itemSlotsScrollRect.content = itemSlotsContent;
            itemSlotsScrollRect.horizontal = true;
            itemSlotsScrollRect.vertical = false;
            itemSlotsScrollRect.movementType = ScrollRect.MovementType.Clamped;
            itemSlotsScrollRect.inertia = true;
            itemSlotsScrollRect.scrollSensitivity = 24f;
        }
    }

    private HUDItemSlot CreateItemSlot(int index)
    {
        GameObject slotObject = new GameObject(
            $"ItemSlot_{index + 1:00}",
            typeof(RectTransform),
            typeof(Image),
            typeof(HUDItemSlot));
        slotObject.transform.SetParent(itemSlotsContent, false);

        RectTransform slotRect = slotObject.GetComponent<RectTransform>();
        slotRect.sizeDelta = new Vector2(80f, 80f);

        Image background = slotObject.GetComponent<Image>();
        background.color = new Color(0.035f, 0.045f, 0.06f, 0.88f);
        background.raycastTarget = false;

        GameObject iconObject = new GameObject("ItemIcon", typeof(RectTransform), typeof(Image));
        iconObject.transform.SetParent(slotObject.transform, false);
        RectTransform iconRect = iconObject.GetComponent<RectTransform>();
        iconRect.anchorMin = new Vector2(0f, 0f);
        iconRect.anchorMax = new Vector2(1f, 1f);
        iconRect.offsetMin = new Vector2(8f, 12f);
        iconRect.offsetMax = new Vector2(-8f, -8f);

        Image icon = iconObject.GetComponent<Image>();
        icon.preserveAspect = true;
        icon.raycastTarget = false;

        HUDItemSlot hudSlot = slotObject.GetComponent<HUDItemSlot>();
        hudSlot.Configure(icon);
        return hudSlot;
    }

    private void RefreshItemSlots()
    {
        FindOrCreateItemSlotsPanel();
        if (itemSlotsPanel == null || itemInventory == null)
            return;

        int nextVisibleCount = 0;
        IReadOnlyList<ItemStackState> ownedItems = itemInventory.OwnedItems;
        for (int i = 0; i < ownedItems.Count; i++)
        {
            ItemStackState state = ownedItems[i];
            if (state == null || state.item == null || state.stackCount <= 0)
                continue;

            while (itemSlots.Count <= nextVisibleCount)
                itemSlots.Add(CreateItemSlot(itemSlots.Count));

            HUDItemSlot slot = itemSlots[nextVisibleCount];
            slot.gameObject.SetActive(true);
            slot.SetIcon(state.item.icon);
            slot.SetStackCount(state.stackCount);
            nextVisibleCount++;
        }

        for (int i = nextVisibleCount; i < itemSlots.Count; i++)
        {
            itemSlots[i].SetIcon(null);
            itemSlots[i].SetStackCount(0);
            itemSlots[i].gameObject.SetActive(false);
        }

        if (itemSlotsContent != null)
        {
            float requiredWidth = Mathf.Max(
                itemSlotsPanel.rect.width,
                8f + nextVisibleCount * 80f + Mathf.Max(0, nextVisibleCount - 1) * 8f);
            itemSlotsContent.sizeDelta = new Vector2(requiredWidth, 0f);
        }

        itemSlotsPanel.gameObject.SetActive(nextVisibleCount > 0);
        if (nextVisibleCount > 0 && itemSlotsScrollRect != null)
        {
            Canvas.ForceUpdateCanvases();
            itemSlotsScrollRect.horizontalNormalizedPosition = 1f;
        }
    }

    private void FindWeaponSlots()
    {
        if(weaponSlots == null || weaponSlots.Length != MaximumInventorySlots)
            weaponSlots = new HUDItemSlot[MaximumInventorySlots];

        Transform panel = transform.Find("PlayerStatusPanel/InventoryPanel/WeaponSlotsPanel");
        if(panel == null)
            return;

        for(int i = 0; i < StartingVisibleInventorySlots; i++)
        {
            if(weaponSlots[i] != null)
                continue;

            Transform slot = panel.Find("WeaponSlot_" + (i + 1).ToString("00"));
            if(slot != null)
                weaponSlots[i] = slot.GetComponent<HUDItemSlot>();
        }

        HUDItemSlot template = weaponSlots[StartingVisibleInventorySlots - 1];
        for(int i = StartingVisibleInventorySlots; i < MaximumInventorySlots; i++)
        {
            if(weaponSlots[i] == null)
                weaponSlots[i] = CreateAdditionalSlot(panel, template, "WeaponSlot", i);
        }
    }

    private void RefreshWeaponSlots()
    {
        if(weaponSlots == null)
            return;

        int visibleSlotCount = ShopUI.GetUnlockedSlotCount(true, StartingVisibleInventorySlots, MaximumInventorySlots);
        for(int i = 0; i < weaponSlots.Length; i++)
        {
            HUDItemSlot hudSlot = weaponSlots[i];
            if(hudSlot == null)
                continue;

            bool unlocked = i < visibleSlotCount;
            hudSlot.gameObject.SetActive(unlocked);
            if(!unlocked)
            {
                hudSlot.SetIcon(null);
                hudSlot.SetLevel(0);
                continue;
            }

            WeaponBehaviour equippedWeapon = weaponInventory != null
                ? weaponInventory.GetWeaponAtSlot(i)
                : null;

            hudSlot.SetIcon(equippedWeapon != null && equippedWeapon.data != null
                ? equippedWeapon.data.icon
                : null);
            hudSlot.SetLevel(equippedWeapon != null ? equippedWeapon.CurrentLevel : 0);
        }
    }

    private void FindTomeSlots()
    {
        if(tomeSlots == null || tomeSlots.Length != MaximumInventorySlots)
            tomeSlots = new HUDItemSlot[MaximumInventorySlots];

        Transform panel = transform.Find("PlayerStatusPanel/InventoryPanel/UpgradeBookSlotsPanel");
        if(panel == null)
            return;

        for(int i = 0; i < StartingVisibleInventorySlots; i++)
        {
            if(tomeSlots[i] != null)
                continue;

            Transform slot = panel.Find("UpgradeBookSlot_" + (i + 1).ToString("00"));
            if(slot != null)
                tomeSlots[i] = slot.GetComponent<HUDItemSlot>();
        }

        HUDItemSlot template = tomeSlots[StartingVisibleInventorySlots - 1];
        for(int i = StartingVisibleInventorySlots; i < MaximumInventorySlots; i++)
        {
            if(tomeSlots[i] == null)
                tomeSlots[i] = CreateAdditionalSlot(panel, template, "UpgradeBookSlot", i);
        }
    }

    private void RefreshTomeSlots()
    {
        if(tomeSlots == null)
            return;

        int visibleSlotCount = ShopUI.GetUnlockedSlotCount(false, StartingVisibleInventorySlots, MaximumInventorySlots);
        for(int i = 0; i < tomeSlots.Length; i++)
        {
            HUDItemSlot hudSlot = tomeSlots[i];
            if(hudSlot == null)
                continue;

            bool unlocked = i < visibleSlotCount;
            hudSlot.gameObject.SetActive(unlocked);
            if(!unlocked)
            {
                hudSlot.SetIcon(null);
                hudSlot.SetLevel(0);
                continue;
            }

            TomeData tome = null;
            int tomeLevel = 0;
            if(tomeInventory != null && i < tomeInventory.OwnedTomes.Count)
            {
                TomeLevelState state = tomeInventory.OwnedTomes[i];
                if(state != null)
                {
                    tome = state.tome;
                    tomeLevel = state.level;
                }
            }

            hudSlot.SetIcon(tome != null ? tome.icon : null);
            hudSlot.SetLevel(tome != null ? tomeLevel : 0);
        }
    }


    private HUDItemSlot CreateAdditionalSlot(Transform parent, HUDItemSlot template, string slotPrefix, int index)
    {
        if(parent == null || template == null)
            return null;

        GameObject slotObject = Instantiate(template.gameObject, parent, false);
        slotObject.name = slotPrefix + "_" + (index + 1).ToString("00");
        RectTransform slotRect = slotObject.GetComponent<RectTransform>();
        if(slotRect != null)
        {
            slotRect.anchorMin = new Vector2(0f, 1f);
            slotRect.anchorMax = new Vector2(0f, 1f);
            slotRect.pivot = new Vector2(0f, 1f);
            slotRect.anchoredPosition = new Vector2(index * 92f, 0f);
            slotRect.sizeDelta = new Vector2(80f, 80f);
        }

        slotObject.SetActive(false);
        HUDItemSlot slot = slotObject.GetComponent<HUDItemSlot>();
        if(slot != null)
        {
            slot.SetIcon(null);
            slot.SetLevel(0);
        }
        return slot;
    }
}
