using UnityEngine;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// Runtime presenter for the survival-game HUD. The scene layout is generated by
/// SurvivalHUDBuilder and all references remain editable in the Inspector.
/// </summary>
public class SurvivalHUD : MonoBehaviour
{
    [Header("Gameplay References")]
    [SerializeField] private PlayerHealth playerHealth;
    [SerializeField] private XPSystem xpSystem;
    [SerializeField] private WeaponInventory weaponInventory;
    [SerializeField] private PlayerTomeInventory tomeInventory;

    [Header("HUD References")]
    [SerializeField] private Image healthFill;
    [SerializeField] private TMP_Text healthText;
    [SerializeField] private Image experienceFill;
    [SerializeField] private Color experienceFillColor = new Color32(34, 217, 111, 255);
    [SerializeField, Min(1f)] private float experienceFillAnimationSpeed = 10f;
    [SerializeField] private TMP_Text experienceText;
    [SerializeField] private TMP_Text levelText;
    [SerializeField] private TMP_Text timerText;
    [SerializeField] private HUDItemSlot[] weaponSlots = new HUDItemSlot[2];
    [SerializeField] private HUDItemSlot[] tomeSlots = new HUDItemSlot[2];

    private float elapsedTime;
    private float targetExperienceFill;
    private float postLevelExperienceFill;
    private bool isAnimatingLevelFill;
    [SerializeField] private TMP_FontAsset displayFont;

    private void Awake()
    {
        ApplyDisplayFont();
        ConfigureExperienceBar();

        if (playerHealth == null)
            playerHealth = FindFirstObjectByType<PlayerHealth>();

        if (xpSystem == null)
            xpSystem = FindFirstObjectByType<XPSystem>();

        if (weaponInventory == null)
            weaponInventory = FindFirstObjectByType<WeaponInventory>();

        if (tomeInventory == null)
            tomeInventory = FindFirstObjectByType<PlayerTomeInventory>();

        FindWeaponSlots();
        FindTomeSlots();
    }

    private void ConfigureExperienceBar()
    {
        if (experienceFill == null) return;

        // Resize the actual green rectangle instead of relying only on Image.fillAmount.
        // This also works reliably when the Image has no source sprite assigned.
        experienceFill.type = Image.Type.Simple;
        experienceFill.color = experienceFillColor;

        RectTransform fillRect = experienceFill.rectTransform;
        fillRect.anchorMin = Vector2.zero;
        fillRect.pivot = new Vector2(0f, 0.5f);
        fillRect.offsetMin = Vector2.zero;
        fillRect.offsetMax = Vector2.zero;
        SetExperienceBarVisual(0f);
    }

    private void SetExperienceBarVisual(float progress)
    {
        if (experienceFill == null) return;

        progress = Mathf.Clamp01(progress);
        experienceFill.fillAmount = progress;

        RectTransform fillRect = experienceFill.rectTransform;
        fillRect.anchorMax = new Vector2(progress, 1f);
        fillRect.offsetMin = Vector2.zero;
        fillRect.offsetMax = Vector2.zero;
    }

    private void ApplyDisplayFont()
    {
        if (displayFont == null) return;

        TMP_Text[] labels = GetComponentsInChildren<TMP_Text>(true);
        foreach (TMP_Text label in labels)
        {
            label.font = displayFont;
            label.fontStyle = FontStyles.Normal;
        }
    }

    private void OnEnable()
    {
        if (xpSystem != null)
        {
            xpSystem.OnXPChanged += HandleXPChanged;
            xpSystem.OnLevelUp += HandleLevelUp;
        }

        if (weaponInventory != null)
            weaponInventory.WeaponsChanged += RefreshWeaponSlots;

        if (tomeInventory != null)
            tomeInventory.TomesChanged += RefreshTomeSlots;

        RefreshExperience(true);
        RefreshWeaponSlots();
        RefreshTomeSlots();
    }

    private void OnDisable()
    {
        if (xpSystem != null)
        {
            xpSystem.OnXPChanged -= HandleXPChanged;
            xpSystem.OnLevelUp -= HandleLevelUp;
        }

        if (weaponInventory != null)
            weaponInventory.WeaponsChanged -= RefreshWeaponSlots;

        if (tomeInventory != null)
            tomeInventory.TomesChanged -= RefreshTomeSlots;
    }

    private void Update()
    {
        elapsedTime += Time.deltaTime;
        RefreshTimer();
        RefreshHealth();
        AnimateExperienceBar();
    }

    private void AnimateExperienceBar()
    {
        if (experienceFill == null) return;

        float blend = 1f - Mathf.Exp(-experienceFillAnimationSpeed * Time.unscaledDeltaTime);
        float displayedProgress = Mathf.Lerp(experienceFill.fillAmount, targetExperienceFill, blend);
        SetExperienceBarVisual(displayedProgress);

        if (Mathf.Abs(experienceFill.fillAmount - targetExperienceFill) > 0.001f) return;

        SetExperienceBarVisual(targetExperienceFill);

        if (!isAnimatingLevelFill || targetExperienceFill < 1f) return;

        // Show the full bar first, then restart from the left for the new level.
        SetExperienceBarVisual(0f);
        targetExperienceFill = postLevelExperienceFill;
        isAnimatingLevelFill = false;
    }

    private void RefreshTimer()
    {
        if (timerText == null) return;

        int totalSeconds = Mathf.FloorToInt(elapsedTime);
        int minutes = totalSeconds / 60;
        int seconds = totalSeconds % 60;
        timerText.text = $"{minutes:00}:{seconds:00}";
    }

    private void RefreshHealth()
    {
        if (playerHealth == null || playerHealth.stats == null) return;

        float maxHealth = Mathf.Max(1f, playerHealth.stats.FinalHp);
        float currentHealth = Mathf.Clamp(playerHealth.currentHp, 0f, maxHealth);

        if (healthFill != null)
            healthFill.fillAmount = currentHealth / maxHealth;

        if (healthText != null)
            healthText.text = $"{Mathf.CeilToInt(currentHealth)} / {Mathf.CeilToInt(maxHealth)}";
    }

    private void RefreshExperience(bool immediate = false)
    {
        if (xpSystem == null) return;

        float progress = Mathf.Clamp01(xpSystem.XPProgress);
        targetExperienceFill = progress;

        if (immediate)
            SetExperienceBarVisual(progress);

        if (experienceText != null)
            experienceText.text = $"XP  {xpSystem.CurrentXP} / {xpSystem.XPToNextLevel}";

        if (levelText != null)
            levelText.text = $"LEVEL {xpSystem.CurrentLevel:00}";
    }

    private void HandleXPChanged(int currentXP, int requiredXP)
    {
        float progress = requiredXP > 0
            ? Mathf.Clamp01((float)currentXP / requiredXP)
            : 0f;

        if (currentXP >= requiredXP)
        {
            targetExperienceFill = 1f;
            postLevelExperienceFill = 0f;
            isAnimatingLevelFill = true;
        }
        else if (isAnimatingLevelFill)
        {
            postLevelExperienceFill = progress;
        }
        else
        {
            targetExperienceFill = progress;
        }

        RefreshExperienceText();
    }

    private void HandleLevelUp(int newLevel)
    {
        if (levelText != null)
            levelText.text = $"LEVEL {newLevel:00}";
    }

    private void RefreshExperienceText()
    {
        if (xpSystem == null) return;

        if (experienceText != null)
            experienceText.text = $"XP  {xpSystem.CurrentXP} / {xpSystem.XPToNextLevel}";

        if (levelText != null)
            levelText.text = $"LEVEL {xpSystem.CurrentLevel:00}";
    }

    private void FindWeaponSlots()
    {
        if (weaponSlots == null || weaponSlots.Length != 2)
            weaponSlots = new HUDItemSlot[2];

        if (weaponSlots[0] == null)
        {
            Transform firstSlot = transform.Find("PlayerStatusPanel/InventoryPanel/WeaponSlotsPanel/WeaponSlot_01");
            if (firstSlot != null)
                weaponSlots[0] = firstSlot.GetComponent<HUDItemSlot>();
        }

        if (weaponSlots[1] == null)
        {
            Transform secondSlot = transform.Find("PlayerStatusPanel/InventoryPanel/WeaponSlotsPanel/WeaponSlot_02");
            if (secondSlot != null)
                weaponSlots[1] = secondSlot.GetComponent<HUDItemSlot>();
        }
    }

    private void RefreshWeaponSlots()
    {
        if (weaponSlots == null)
            return;

        for (int i = 0; i < weaponSlots.Length; i++)
        {
            HUDItemSlot hudSlot = weaponSlots[i];
            if (hudSlot == null)
                continue;

            WeaponBehaviour equippedWeapon = weaponInventory != null
                ? weaponInventory.GetWeaponAtSlot(i)
                : null;

            hudSlot.SetIcon(equippedWeapon != null && equippedWeapon.data != null
                ? equippedWeapon.data.icon
                : null);
            hudSlot.SetLevel(equippedWeapon != null ? equippedWeapon.CurrentLevel : 0);
        }
    }

    private void FindTomeSlots()
    {
        if (tomeSlots == null || tomeSlots.Length != 2)
            tomeSlots = new HUDItemSlot[2];

        if (tomeSlots[0] == null)
        {
            Transform firstSlot = transform.Find("PlayerStatusPanel/InventoryPanel/UpgradeBookSlotsPanel/UpgradeBookSlot_01");
            if (firstSlot != null)
                tomeSlots[0] = firstSlot.GetComponent<HUDItemSlot>();
        }

        if (tomeSlots[1] == null)
        {
            Transform secondSlot = transform.Find("PlayerStatusPanel/InventoryPanel/UpgradeBookSlotsPanel/UpgradeBookSlot_02");
            if (secondSlot != null)
                tomeSlots[1] = secondSlot.GetComponent<HUDItemSlot>();
        }
    }

    private void RefreshTomeSlots()
    {
        if (tomeSlots == null)
            return;

        for (int i = 0; i < tomeSlots.Length; i++)
        {
            HUDItemSlot hudSlot = tomeSlots[i];
            if (hudSlot == null)
                continue;

            TomeData tome = null;
            int tomeLevel = 0;
            if (tomeInventory != null && i < tomeInventory.OwnedTomes.Count)
            {
                TomeLevelState state = tomeInventory.OwnedTomes[i];
                if (state != null)
                {
                    tome = state.tome;
                    tomeLevel = state.level;
                }
            }

            hudSlot.SetIcon(tome != null ? tome.icon : null);
            hudSlot.SetLevel(tome != null ? tomeLevel : 0);
        }
    }
}
